# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config", ".flake8"]
        language_version: '3.11'
  - repo: 'https://github.com/psf/black'
    rev: 24.3.0
    hooks:
      - id: black
        language_version: "3.11"
        pass_filenames: false
        args: ["--check", "."]
        additional_dependencies: ["flake8-black"]
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: 'https://github.com/mgedmin/check-manifest'
    rev: "0.51"
    hooks:
      - id: check-manifest
  - repo: local
    hooks:
      - id: check-bump
        name: check-bump
        language: python
        entry: .ci/scripts/check_bump.sh
        pass_filenames: false
        additional_dependencies: ["bump-my-version"]
      - id: check-requirements
        name: check-requirements
        language: python
        entry: python .ci/scripts/check_requirements.py
        pass_filenames: false
        additional_dependencies: ["packaging"]
      - id: check-gettext
        name: check-gettext
        language: unsupported_script
        types: [python]
        entry: .ci/scripts/check_gettext.sh
      - id: extra-lint
        name: extra-lint
        language: unsupported
        entry: sh -c "[ ! -x .ci/scripts/extra_linting.sh ] || .ci/scripts/extra_linting.sh"
        pass_filenames: false
