# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # -   id: trailing-whitespace
    # -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: ["--config", ".flake8"]
        language_version: "3.11"
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
    -   id: black
        args: ["--check", "--diff", "."]
        additional_dependencies: ["flake8-black"]
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
    -   id: yamllint

    
