api_root: /pulp/
black: true
check_commit_message: true
check_gettext: true
check_manifest: true
check_stray_pulpcore_imports: false
ci_base_image: ghcr.io/pulp/pulp-ci-centos9
ci_env: {}
ci_trigger: '{pull_request: {branches: [''*'']}}'
cli_package: pulp-cli
cli_repo: https://github.com/pulp/pulp-cli.git
core_import_allowed: []
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_to_pypi: true
disabled_redis_runners:
- s3
docker_fixtures: true
extra_files: []
flake8: true
flake8_ignore:
- ./pulpcore/app/protobuf/*
github_org: pulp
latest_release_branch: null
lint_requirements: true
os_required_packages: []
parallel_test_workers: 8
plugin_app_label: core
plugin_default_branch: main
plugin_name: pulpcore
plugins:
- app_label: core
  name: pulpcore
post_job_template: null
pre_job_template: null
pulp_env:
  PULP_CA_BUNDLE: /etc/pulp/certs/pulp_webserver.crt
pulp_env_azure: {}
pulp_env_gcp: {}
pulp_env_s3: {}
pulp_scheme: https
pulp_settings:
  allowed_export_paths:
  - /tmp
  allowed_import_paths:
  - /tmp
  orphan_protection_time: 0
pulp_settings_azure:
  MEDIA_ROOT: ''
  STORAGES:
    default:
      BACKEND: storages.backends.azure_storage.AzureStorage
      OPTIONS:
        account_key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
        account_name: devstoreaccount1
        connection_string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ci-azurite:10000/devstoreaccount1;
        azure_container: pulp-test
        location: pulp3
        overwrite_files: true
        expiration_secs: 120
    staticfiles:
      BACKEND: django.contrib.staticfiles.storage.StaticFilesStorage
  domain_enabled: true
pulp_settings_gcp: null
pulp_settings_s3:
  MEDIA_ROOT: ''
  domain_enabled: true
  hide_guarded_distributions: true
  STORAGES:
    default:
      BACKEND: storages.backends.s3boto3.S3Boto3Storage
      OPTIONS:
        access_key: AKIAIT2Z5TDYPX3ARJBA
        secret_key: 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
        bucket_name: pulp3
        endpoint_url: http://minio:9000
        region_name: eu-central-1
        signature_version: s3v4
        addressing_style: path
        default_acl: '@none'
    staticfiles:
      BACKEND: django.contrib.staticfiles.storage.StaticFilesStorage
pydocstyle: true
release_email: pulp-infra@redhat.com
release_user: pulpbot
stalebot: true
stalebot_days_until_close: 30
stalebot_days_until_stale: 90
stalebot_limit_to_pulls: true
supported_release_branches:
- '3.16'
- '3.18'
- '3.21'
- '3.22'
- '3.23'
- '3.27'
sync_ci: true
test_azure: true
test_cli: true
test_deprecations: true
test_gcp: false
test_lowerbounds: true
test_performance: false
test_reroute: true
test_s3: true
use_issue_template: true
