# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

# pulp_file is hardcoded in plugin_template when generating for pulpcore in some
# places. In other places, plugin_template uses generic logic for it, so we
# specify it here.
# Also, .travis/pre_before_install.sh reads the pulp_file branch. At runtime,
# not template generation time.
additional_plugins:
- { name: pulp_file, branch: 0.1 }
- { name: pulp-certguard, branch: master }
black: false
check_commit_message: true
coverage: true
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docs_test: true
plugin_app_label: pulpcore
plugin_camel: Pulpcore
plugin_camel_short: Pulpcore
plugin_caps: PULPCORE
plugin_caps_short: PULPCORE
plugin_dash: pulpcore
plugin_dash_short: pulpcore
plugin_name: pulpcore
plugin_snake: pulpcore
pulp_settings: null
pulpcore_branch: null
pydocstyle: true
pypi_username: pulp
test_bindings: true
test_performance: false
travis_notifications:
  irc:
    channels:
    - chat.freenode.net#pulp-build
    on_failure: always
    on_success: change
    template:
    - '%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author} : %{commit_subject})'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - '%{message}'

