# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_repos:
- branch: master
  name: pulp_file
- branch: master
  name: pulp-certguard
black: true
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: false
cherry_pick_automation: false
coverage: true
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: true
docs_test: true
flake8: true
issue_tracker: redmine
plugin_app_label: core
plugin_camel: Pulpcore
plugin_camel_short: Pulpcore
plugin_caps: PULPCORE
plugin_caps_short: PULPCORE
plugin_dash: pulpcore
plugin_dash_short: pulpcore
plugin_default_branch: master
plugin_name: pulpcore
plugin_snake: pulpcore
publish_docs_to_pulpprojectdotorg: true
pulp_scheme: http
pulp_settings:
  allowed_export_paths:
  - /tmp
  allowed_import_paths:
  - /tmp
pulpcore_branch: null
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: d1a778bda808
pydocstyle: true
pypi_username: pulp
redmine_project: pulp
release_user: pulpbot
stable_branch: null
sync_ci: true
test_bindings: true
test_cli: true
test_fips_nightly: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: true
update_redmine: true
upgrade_range:
- pulp-certguard_branch: 1.2
  pulp_file_branch: 1.6
  pulpcore_branch: 3.11

