# Ansible playbook to create the pulp service containers image
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yaml
  tasks:
    - name: "Generate Containerfile from template"
      template:
        src: Containerfile.j2
        dest: Containerfile

    - name: "Build pulp image"
      # We build from the ../.. (parent dir of pulpcore git repo) Docker build
      # "context" so that repos like pulp-smash are accessible to Docker
      # build. So that PR branches can be used via relative paths.
      #
      # We default to using the docker build / podman buildah cache, for
      # 1-off-builds and Travis CI purposes (which has no cache across CI runs.)
      # Run build.yaml with -e cache=false if your builds are using outdated
      # layers.
      command: "docker build --network host --no-cache={{ not cache | default(true) | bool }} -t {{ image.name }}:{{ image.tag }} -f {{ playbook_dir }}/Containerfile ../.."

    - name: "Clean image cache"
      docker_prune:
        images : true
...
