---
- hosts: all
  pre_tasks:
    - name: Load DB variables
      include_vars: '{{ pulp_db_type }}.yml'
  vars:
    pulp_default_admin_password: admin
    pulp_secret_key: secret
    pulp_source_dir: '/home/travis/build/pulp/pulpcore/'
    pulp_plugin_source_dir: "/home/travis/build/pulp/pulpcore-plugin"
    pulp_install_plugins:
      pulp-file:
        app_label: "file"
        source_dir: "/home/travis/build/pulp/pulp_file"
      pulp-certguard:
        app_label: "certguard"
        source_dir: "/home/travis/build/pulp/pulp-certguard"
    ansible_python_interpreter: '/opt/pyenv/shims/python3'
    pulp_user: 'travis'
    developer_user: 'travis'
    pulp_install_db: false
    pulp_db_user: 'travis'
    pulp_db_password: ''
    pulp_preq_packages: []
    pulp_content_host: 'localhost:24816'
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
  roles:
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
